nfs:
  hosts:
    172.31.11.165:
      ansible_user: ec2-user

webservers:
  hosts:
    172.31.10.19:
      ansible_user: ec2-user
    172.31.12.81:
      ansible_user: ec2-user

db:
  hosts:
    172.31.14.241:
      ansible_user: ec2-user

lb:
  hosts:
    172.31.2.61:
      ansible_user: ubuntu





















